### ISSUE TITLE
This is not working?

### ISSUE THREAD

**Issue by kaumudpa** [jamesgrams/instagram-poster#1]
i keep getting the error:

```
  at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:5627) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Can you help me with this?

**Comment by chetan-cueclad** [comment]
Even i am getting error while making this work:

Here is my Log: 

```
launching puppeteer
visiting the instagram login page
waiting for the username input
typing in the username and password
clicking log in
going to instagram home
waiting for the file inputs
clicking new post
uploading the image
waiting for next
clicking next
adding the caption
waiting for share
clicking share
(node:57572) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'click' of undefined
    at run (/Users/abc/Desktop/instagram-poster-master/index.js:166:20)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:57572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:57572) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Any help will be appreciated.

**Comment by jamesgrams** [comment]
Thanks for the log, @chetan-cueclad.

I was able to reproduce the error. I just pushed an update that should fix it (2f34a436eb1867d370f002d57063a32427ac2cb4). The code wasn't explicitly waiting for the share button to become available, it was just trying to click it. In some cases, the share button wasn't loaded yet. 

Let me know if you are still having problems @kaumudpa @chetan-cueclad.

**Comment by chetan-cueclad** [comment]
This is working wonderfully. 

Thank you so much!

:)

**Comment by kaumudpa** [comment]
Yup!

**Comment by jamesgrams** [comment]
No problem :)
I'll close the issue
